### ISSUE TITLE
Please add an License

### ISSUE THREAD

**Issue by pluvium27** [wolf71/TinyWebDav#7]
Can you add an open source license to this repo? I don't know how to use it in my project legally. Thank you

**Comment by wolf71** [comment]
MIT

**Comment by stefan6419846** [comment]
This should probably be reflected in the repository and its files as well. The files currently have a reference to *pandav*, which is under the Artistic License (Artistic-1.0 to be precise, judging from https://sourceforge.net/p/pandav/code/).
